EmployeeData/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using EmployeeData.Models;
using EmployeeData.Models.Service;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;

namespace Test.Controllers
{
   
    [TypeFilter(typeof(DebugLogAttribute))]
    [Route("Testing")]
    public class EmployeeController : Controller
    {
        private readonly IMemoryCache _memoryCache;
        ModelView employeeViewModel;


        public EmployeeController(IMemoryCache memoryCache)
        {
            employeeViewModel = new ModelView();
            employeeViewModel.Employees.Add(new Employee()
            {

                Id = 1,
                EmployeeName = "Ankita",
                EmployeeAge = 22,
                EmployeeSalary = 32000

            });

            employeeViewModel.Employees.Add(new Employee()
            {
                Id = 2,
                EmployeeName = "Nikita",
                EmployeeAge = 26,
                EmployeeSalary = 35000
            });

            employeeViewModel.Employees.Add(new Employee()
            {
                Id = 3,
                EmployeeName = "Prashant",
                EmployeeAge = 24,
                EmployeeSalary = 50000

            });

            for (int i = 0; i <= 60; i++)
            {
                employeeViewModel.AgeDetails.Add(new Age
                {
                    Id = i,
                    Name = i

                });
            }
            _memoryCache = memoryCache;
        }
        [Route("")]
        public IActionResult Index(string id)
        {
            int empId = Convert.ToInt32(Common.DecryptString(id));
            List<SelectListItem> ObjList = new List<SelectListItem>();
            for(int i=0;i<= 60;i++)
            {
                ObjList.Add(new SelectListItem { Text = i.ToString(), Value = i.ToString() });
            }
            ViewBag.AgeList = employeeViewModel.AgeDetails;
            return View(employeeViewModel.Employees.FirstOrDefault(x => x.Id == empId));
        }
        [Route("Employees")]
        public IActionResult EmployeeList()
        {
            var CacheKey = "employeeList";
            if (!_memoryCache.TryGetValue(CacheKey, out ModelView employeeList))
            {
                employeeList = employeeViewModel;
                var cacheExpiryOptions = new MemoryCacheEntryOptions
                {
                    AbsoluteExpiration = DateTime.Now.AddSeconds(50),
                    Priority = CacheItemPriority.High,
                    SlidingExpiration = TimeSpan.FromSeconds(20)
                };
                _memoryCache.Set(CacheKey, employeeList, cacheExpiryOptions);
            }
                return View(employeeViewModel);
        }
    }
}

EmployeeData/Views/Employee/EmployeeList.cshtml
@model ModelView

<b> Employee List </b>
<br/>
<div class="row">
    <my-first-tag-helper name="Test" desc="This is for testing purpose">

    </my-first-tag-helper>
</div>
<div class="container">
@Html.Partial("_Employee",Model.Employees)

</div>

EmployeeData/Views/Employee/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Employee

<b>Index Page</b>

<br/>
<br/>

<div>
   @Html.HiddenFor(x=>x.Id)
   @Html.LabelFor(x=>x.EmployeeName):<input type="text" value="@Model.EmployeeName"/>
   @Html.LabelFor(x=>x.EmployeeName):@Html.TextBox("Emp",@Model.EmployeeName)
   @Html.LabelFor(x=>x.EmployeeName):@Html.TextBoxFor(x=>x.EmployeeName)
      <br/>
       @Html.LabelFor(x=>x.EmployeeSalary):@Model.EmployeeSalary
       <br/>
   @Html.LabelFor(x=>x.EmployeeAge):@Model.EmployeeAge:@Html.DropDownListFor(x => x.EmployeeAge, (IEnumerable<SelectListItem>)ViewBag.AgeList)
   @*
       @Html.DropDownList("EmployeeAge", ViewBag.AgeList, "Id","Name" )
   *@
 
    @**@
       

</div>

EmployeeData/Views/Employee/_Employee.cshtml
@model List<Employee>
@using  EmployeeData.Models.Service
   <table class="table">
       <thead>
           <tr>
               <th scope="col">#</th>
               <th scope="col">Name</th>
               <th scope="col">Age</th>
               <th scope="col">Salary</th>
           </tr>
       </thead>
       <tbody>
              @foreach (var item in Model)
       {
           <tr>
                <td>@Html.ActionLink(item.EmployeeName,"Index","Employee", new { id =Common.EnryptString( item.Id.ToString() )})</td>
                <td>@item.EmployeeName</td>
                <td>@item.EmployeeAge</td>
                <td>@item.EmployeeSalary</td>
             </tr>
       }
     </tbody>
   </table>

   